"""Architecture registry -- single source of truth for architecture-specific config."""

from __future__ import annotations

from typing import Any

ARCH_REGISTRY: dict[str, dict[str, Any]] = {
    "wan22_t2v": {
        "display_name": "WAN 2.2 T2V",
        "aliases": ["wan22-t2v", "wan-t2v-a14b"],
        "runtime_arch_short": "wan",
        "runtime_arch_full": "wan",
        # CRITICAL: task MUST be in required_variant_args so it appears in compiled output.
        # argparse default is "t2v-14B" (WAN 2.1!) -- omitting silently uses wrong config.
        "required_variant_args": {"task": "t2v-A14B"},
        "train_script": "wan_train_network.py",
        "cache_latents_script": "wan_cache_latents.py",
        "cache_te_script": "wan_cache_text_encoder_outputs.py",
        "generate_script": "wan_generate_video.py",
        "network_module": "networks.lora_wan",
        "model_files": {
            "dit": "${machine.models_dir}/WAN/Wan-2.2-T2V-Low-Noise-BF16.safetensors",
            "dit_high_noise": "${machine.models_dir}/WAN/Wan-2.2-T2V-High-Noise-BF16.safetensors",
            "vae": "${machine.models_dir}/WAN/Wan2_1_VAE_bf16.safetensors",
            "t5": "${machine.models_dir}/WAN/umt5-xxl-enc-bf16.safetensors",
        },
        "defaults": {
            "timestep_sampling": "shift",
            "discrete_flow_shift": 12.0,
            "timestep_boundary": 0.875,
            "sigmoid_scale": 2.0,
            "flash_attn": True,
            "rope_func": "comfy",
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024], [512, 512], [256, 256]],
            "video_target_frames": [1, 17, 33, 49, 81],
            "frame_extraction": "head",
            "source_fps": 30.0,
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": True,
            "cfg_schedule": True,
            "cfgzerostar": True,
            "nag": True,
            "riflex": True,
            "v2v": True,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {
            "gradient_accumulation_steps": {
                "max_recommended": 1,
                "message": (
                    "Dual-expert training with GA>1 mixes experts within accumulation groups, "
                    "increasing noise. Consider batch_size>1 instead."
                ),
            },
        },
        "constraints": {},
        "cache_suffix": "wan22_t2v",
    },
    "qwen_image": {
        "display_name": "Qwen-Image",
        "aliases": ["qwen", "qwen-image", "qwen_image_2512"],
        "runtime_arch_short": "qi",
        "runtime_arch_full": "qwen_image",
        "required_variant_args": {},
        "train_script": "qwen_image_train_network.py",
        "cache_latents_script": "qwen_image_cache_latents.py",
        "cache_te_script": "qwen_image_cache_text_encoder_outputs.py",
        "generate_script": "qwen_image_generate_image.py",
        "network_module": "networks.lora_qwen_image",
        "model_files": {
            "dit": "${machine.models_dir}/qwen-image/Qwen_Image_2512_BF16.safetensors",
            "text_encoder": "${machine.models_dir}/qwen-image/qwen_2.5_vl_7b_bf16.safetensors",
            "vae": "${machine.models_dir}/qwen-image/qwen_train_vae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "qwen_shift",
            "discrete_flow_shift": 2.2,
            "model_version": "original",
        },
        "dataset_defaults": {
            "default_resolutions": [[1328, 1328]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": True,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "qwen_image",
    },
    "flux2_klein9b": {
        "display_name": "FLUX.2 Klein-base-9B",
        "aliases": ["flux2-klein-9b", "flux2-klein9b", "klein-base-9b"],
        "runtime_arch_short": "f2k9b",
        "runtime_arch_full": "flux_2_klein_9b",
        # model_version must match FLUX2_MODEL_INFO key -- controls block counts, params, and fixed_params
        "required_variant_args": {"model_version": "klein-base-9b"},
        "train_script": "flux_2_train_network.py",
        "cache_latents_script": "flux_2_cache_latents.py",
        "cache_te_script": "flux_2_cache_text_encoder_outputs.py",
        "generate_script": "flux_2_generate_image.py",
        "network_module": "networks.lora_flux_2",
        "model_files": {
            "dit": "${machine.models_dir}/flux-2-klein-base-9b.safetensors",
            "text_encoder": "${machine.models_dir}/text_encoder/model-00001-of-00004.safetensors",
            "vae": "${machine.models_dir}/flux2/ae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "flux2_shift",
            "weighting_scheme": "none",
            "model_version": "klein-base-9b",
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "flux2klein9b",
    },
    "wan22_i2v": {
        "display_name": "WAN 2.2 I2V",
        "aliases": ["wan22-i2v", "wan-i2v-a14b"],
        "runtime_arch_short": "wan",
        "runtime_arch_full": "wan",
        "required_variant_args": {"task": "i2v-A14B"},
        "train_script": "wan_train_network.py",
        "cache_latents_script": "wan_cache_latents.py",
        "cache_te_script": "wan_cache_text_encoder_outputs.py",
        "generate_script": "wan_generate_video.py",
        "network_module": "networks.lora_wan",
        "model_files": {
            "dit": "${machine.models_dir}/WAN/Wan-2.2-I2V-14B-480P-BF16.safetensors",
            "vae": "${machine.models_dir}/WAN/Wan2_1_VAE_bf16.safetensors",
            "t5": "${machine.models_dir}/WAN/umt5-xxl-enc-bf16.safetensors",
            "clip": "${machine.models_dir}/WAN/clip_open-clip-xlm-roberta-large-ViT-H-14-frozen.safetensors",
        },
        "defaults": {
            "timestep_sampling": "shift",
            "discrete_flow_shift": 5.0,
            "timestep_boundary": 0.900,
            "sigmoid_scale": 2.0,
            "flash_attn": True,
            "rope_func": "comfy",
        },
        "dataset_defaults": {
            "default_resolutions": [[480, 832]],
            "video_target_frames": [1, 17, 33, 49, 81],
            "frame_extraction": "head",
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": True,
            "cfg_schedule": True,
            "cfgzerostar": True,
            "nag": True,
            "riflex": True,
            "v2v": True,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {
            "gradient_accumulation_steps": {
                "max_recommended": 1,
                "message": "Dual-expert training with GA>1 mixes experts within accumulation groups.",
            },
        },
        "constraints": {},
        "cache_suffix": "wan22_i2v",
    },
    "hv": {
        "display_name": "HunyuanVideo",
        "aliases": ["hunyuan", "hunyuan-video"],
        "runtime_arch_short": "hv",
        "runtime_arch_full": "hunyuan_video",
        "required_variant_args": {},
        "train_script": "hv_train_network.py",
        "cache_latents_script": "cache_latents.py",
        "cache_te_script": "cache_text_encoder_outputs.py",
        "generate_script": "hv_generate_video.py",
        "network_module": "networks.lora",
        "model_files": {
            "dit": "${machine.models_dir}/hunyuan-video/hunyuan_video_720_bf16.safetensors",
            "vae": "${machine.models_dir}/hunyuan-video/hunyuan_video_vae_fp32.safetensors",
            "text_encoder1": "${machine.models_dir}/hunyuan-video/llava_llama3_fp16.safetensors",
            "text_encoder2": "${machine.models_dir}/hunyuan-video/clip_l_fp16.safetensors",
        },
        "defaults": {
            "timestep_sampling": "sigmoid",
            "sigmoid_scale": 1.0,
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[544, 960]],
            "video_target_frames": [1, 17, 33, 49],
            "frame_extraction": "head",
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": True,
            "cfg_schedule": True,
            "cfgzerostar": True,
            "nag": False,
            "riflex": True,
            "v2v": True,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "hv",
    },
    "hv_1_5": {
        "display_name": "HunyuanVideo 1.5",
        "aliases": ["hunyuan-1.5", "hv15", "hunyuan-video-1.5"],
        "runtime_arch_short": "hv15",
        "runtime_arch_full": "hunyuan_video_1_5",
        "required_variant_args": {},
        "train_script": "hv_1_5_train_network.py",
        "cache_latents_script": "hv_1_5_cache_latents.py",
        "cache_te_script": "hv_1_5_cache_text_encoder_outputs.py",
        "generate_script": "hv_1_5_generate_video.py",
        "network_module": "networks.lora_hv_1_5",
        "model_files": {
            "dit": "${machine.models_dir}/hunyuan-video-1.5/hunyuan_video_1_5_bf16.safetensors",
            "vae": "${machine.models_dir}/hunyuan-video-1.5/hunyuan_video_vae_fp32.safetensors",
            "text_encoder": "${machine.models_dir}/hunyuan-video-1.5/qwen2_5_vl_bf16.safetensors",
        },
        "defaults": {
            "timestep_sampling": "sigmoid",
            "sigmoid_scale": 1.0,
        },
        "dataset_defaults": {
            "default_resolutions": [[544, 960]],
            "video_target_frames": [1, 17, 33, 49],
            "frame_extraction": "head",
        },
        "supports": {
            "mask_loss": False,
            "prior_preservation": False,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "hv15",
    },
    "framepack": {
        "display_name": "FramePack",
        "aliases": ["fpack", "fp"],
        "runtime_arch_short": "fp",
        "runtime_arch_full": "framepack",
        "required_variant_args": {},
        "train_script": "fpack_train_network.py",
        "cache_latents_script": "fpack_cache_latents.py",
        "cache_te_script": "fpack_cache_text_encoder_outputs.py",
        "generate_script": "fpack_generate_video.py",
        "network_module": "networks.lora_framepack",
        "model_files": {
            "dit": "${machine.models_dir}/framepack/framepack_bf16.safetensors",
            "vae": "${machine.models_dir}/framepack/hunyuan_video_vae_fp32.safetensors",
            "text_encoder": "${machine.models_dir}/framepack/llava_llama3_fp16.safetensors",
        },
        "defaults": {
            "timestep_sampling": "sigmoid",
            "sigmoid_scale": 1.0,
        },
        "dataset_defaults": {
            "default_resolutions": [[512, 512]],
            "video_target_frames": [1, 17, 33],
            "frame_extraction": "head",
        },
        "supports": {
            "mask_loss": False,
            "prior_preservation": False,
            "latent_preview": True,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "framepack",
    },
    "flux_kontext": {
        "display_name": "FLUX.1 Kontext",
        "aliases": ["kontext", "flux-kontext"],
        "runtime_arch_short": "fk",
        "runtime_arch_full": "flux_kontext",
        "required_variant_args": {},
        "train_script": "flux_kontext_train_network.py",
        "cache_latents_script": "flux_kontext_cache_latents.py",
        "cache_te_script": "flux_kontext_cache_text_encoder_outputs.py",
        "generate_script": "flux_kontext_generate_image.py",
        "network_module": "networks.lora_flux",
        "model_files": {
            "dit": "${machine.models_dir}/flux-kontext/flux1-kontext-dev.safetensors",
            "ae": "${machine.models_dir}/flux-kontext/ae.safetensors",
            "clip": "${machine.models_dir}/flux-kontext/clip_l.safetensors",
            "t5": "${machine.models_dir}/flux-kontext/t5xxl_fp16.safetensors",
        },
        "defaults": {
            "timestep_sampling": "sigmoid",
            "sigmoid_scale": 1.0,
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024]],
        },
        "supports": {
            "mask_loss": False,
            "prior_preservation": False,
            "latent_preview": True,
            "cfg_schedule": True,
            "cfgzerostar": True,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "flux_kontext",
    },
    "flux2_dev": {
        "display_name": "FLUX.2 Dev",
        "aliases": ["flux2-dev", "flux2"],
        "runtime_arch_short": "f2d",
        "runtime_arch_full": "flux_2_dev",
        "required_variant_args": {"model_version": "dev"},
        "train_script": "flux_2_train_network.py",
        "cache_latents_script": "flux_2_cache_latents.py",
        "cache_te_script": "flux_2_cache_text_encoder_outputs.py",
        "generate_script": "flux_2_generate_image.py",
        "network_module": "networks.lora_flux_2",
        "model_files": {
            "dit": "${machine.models_dir}/flux2/flux2-dev.safetensors",
            "text_encoder": "${machine.models_dir}/flux2/text_encoder",
            "vae": "${machine.models_dir}/flux2/ae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "flux2_shift",
            "weighting_scheme": "none",
            "model_version": "dev",
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "flux2dev",
    },
    "flux2_klein4b": {
        "display_name": "FLUX.2 Klein-base-4B",
        "aliases": ["flux2-klein-4b", "flux2-klein4b", "klein-base-4b"],
        "runtime_arch_short": "f2k4b",
        "runtime_arch_full": "flux_2_klein_4b",
        "required_variant_args": {"model_version": "klein-base-4b"},
        "train_script": "flux_2_train_network.py",
        "cache_latents_script": "flux_2_cache_latents.py",
        "cache_te_script": "flux_2_cache_text_encoder_outputs.py",
        "generate_script": "flux_2_generate_image.py",
        "network_module": "networks.lora_flux_2",
        "model_files": {
            "dit": "${machine.models_dir}/flux-2-klein-base-4b.safetensors",
            "text_encoder": "${machine.models_dir}/flux2/text_encoder_qwen3_4b",
            "vae": "${machine.models_dir}/flux2/ae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "flux2_shift",
            "weighting_scheme": "none",
            "model_version": "klein-base-4b",
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "flux2klein4b",
    },
    "flux2_klein4b_distil": {
        "display_name": "FLUX.2 Klein-4B (distilled)",
        "aliases": ["flux2-klein-4b-distil", "klein-4b"],
        "runtime_arch_short": "f2k4b",
        "runtime_arch_full": "flux_2_klein_4b",
        "required_variant_args": {"model_version": "klein-4b"},
        "train_script": "flux_2_train_network.py",
        "cache_latents_script": "flux_2_cache_latents.py",
        "cache_te_script": "flux_2_cache_text_encoder_outputs.py",
        "generate_script": "flux_2_generate_image.py",
        "network_module": "networks.lora_flux_2",
        "model_files": {
            "dit": "${machine.models_dir}/flux-2-klein-4b.safetensors",
            "text_encoder": "${machine.models_dir}/flux2/text_encoder_qwen3_4b",
            "vae": "${machine.models_dir}/flux2/ae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "flux2_shift",
            "weighting_scheme": "none",
            "model_version": "klein-4b",
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "flux2klein4b",  # Shared with klein-base-4b — same VAE, caches interchangeable
    },
    "flux2_klein9b_distil": {
        "display_name": "FLUX.2 Klein-9B (distilled)",
        "aliases": ["flux2-klein-9b-distil", "klein-9b"],
        "runtime_arch_short": "f2k9b",
        "runtime_arch_full": "flux_2_klein_9b",
        "required_variant_args": {"model_version": "klein-9b"},
        "train_script": "flux_2_train_network.py",
        "cache_latents_script": "flux_2_cache_latents.py",
        "cache_te_script": "flux_2_cache_text_encoder_outputs.py",
        "generate_script": "flux_2_generate_image.py",
        "network_module": "networks.lora_flux_2",
        "model_files": {
            "dit": "${machine.models_dir}/flux-2-klein-9b.safetensors",
            "text_encoder": "${machine.models_dir}/flux2/text_encoder_qwen3_8b",
            "vae": "${machine.models_dir}/flux2/ae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "flux2_shift",
            "weighting_scheme": "none",
            "model_version": "klein-9b",
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "flux2klein9b",
    },
    "qwen_image_edit": {
        "display_name": "Qwen-Image Edit",
        "aliases": ["qwen-edit", "qwen-image-edit"],
        "runtime_arch_short": "qie",
        "runtime_arch_full": "qwen_image_edit",
        "required_variant_args": {},
        "train_script": "qwen_image_train_network.py",
        "cache_latents_script": "qwen_image_cache_latents.py",
        "cache_te_script": "qwen_image_cache_text_encoder_outputs.py",
        "generate_script": "qwen_image_generate_image.py",
        "network_module": "networks.lora_qwen_image",
        "model_files": {
            "dit": "${machine.models_dir}/qwen-image/Qwen_Image_Edit_2512_BF16.safetensors",
            "text_encoder": "${machine.models_dir}/qwen-image/qwen_2.5_vl_7b_bf16.safetensors",
            "vae": "${machine.models_dir}/qwen-image/qwen_train_vae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "qwen_shift",
            "discrete_flow_shift": 2.2,
            "model_version": "edit",
        },
        "dataset_defaults": {
            "default_resolutions": [[1328, 1328]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": True,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "qwen_image_edit",
    },
    "qwen_image_layered": {
        "display_name": "Qwen-Image Layered",
        "aliases": ["qwen-layered", "qwen-image-layered"],
        "runtime_arch_short": "qil",
        "runtime_arch_full": "qwen_image_layered",
        "required_variant_args": {},
        "train_script": "qwen_image_train_network.py",
        "cache_latents_script": "qwen_image_cache_latents.py",
        "cache_te_script": "qwen_image_cache_text_encoder_outputs.py",
        "generate_script": "qwen_image_generate_image.py",
        "network_module": "networks.lora_qwen_image",
        "model_files": {
            "dit": "${machine.models_dir}/qwen-image/Qwen_Image_Layered_2512_BF16.safetensors",
            "text_encoder": "${machine.models_dir}/qwen-image/qwen_2.5_vl_7b_bf16.safetensors",
            "vae": "${machine.models_dir}/qwen-image/qwen_train_vae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "qwen_shift",
            "discrete_flow_shift": 2.2,
            "model_version": "layered",
        },
        "dataset_defaults": {
            "default_resolutions": [[1328, 1328]],
        },
        "supports": {
            "mask_loss": True,
            # Prior preservation raises NotImplementedError for layout="layered"
            "prior_preservation": False,
            "latent_preview": False,
            "cfg_schedule": False,
            "cfgzerostar": False,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": True,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "qwen_image_layered",
    },
    "zimage_base": {
        "display_name": "Z-Image Base",
        "aliases": ["zimage", "z-image", "z-image-base"],
        "runtime_arch_short": "zi",
        "runtime_arch_full": "z_image",
        "required_variant_args": {},
        "train_script": "zimage_train_network.py",
        "cache_latents_script": "zimage_cache_latents.py",
        "cache_te_script": "zimage_cache_text_encoder_outputs.py",
        "generate_script": "zimage_generate_image.py",
        "network_module": "networks.lora_zimage",
        "model_files": {
            "dit": "${machine.models_dir}/zimage/z-image-base.safetensors",
            "text_encoder": "${machine.models_dir}/zimage/text_encoder_qwen3",
            "vae": "${machine.models_dir}/zimage/ae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "sigmoid",
            "sigmoid_scale": 1.0,
            "discrete_flow_shift": 3.0,
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": True,
            "cfg_schedule": True,
            "cfgzerostar": True,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "zimage",
    },
    "zimage_turbo": {
        "display_name": "Z-Image Turbo",
        "aliases": ["z-image-turbo"],
        "runtime_arch_short": "zi",
        "runtime_arch_full": "z_image",
        "required_variant_args": {},
        "train_script": "zimage_train_network.py",
        "cache_latents_script": "zimage_cache_latents.py",
        "cache_te_script": "zimage_cache_text_encoder_outputs.py",
        "generate_script": "zimage_generate_image.py",
        "network_module": "networks.lora_zimage",
        "model_files": {
            "dit": "${machine.models_dir}/zimage/z-image-turbo.safetensors",
            "text_encoder": "${machine.models_dir}/zimage/text_encoder_qwen3",
            "vae": "${machine.models_dir}/zimage/ae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "sigmoid",
            "sigmoid_scale": 1.0,
            "discrete_flow_shift": 3.0,
            "flash_attn": True,
        },
        "dataset_defaults": {
            "default_resolutions": [[1024, 1024]],
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": True,
            "cfg_schedule": True,
            "cfgzerostar": True,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "zimage",  # Shared with zimage_base — same VAE, caches interchangeable
    },
    "kandinsky5": {
        "display_name": "Kandinsky 5",
        "aliases": ["k5", "kandinsky"],
        "runtime_arch_short": "k5",
        "runtime_arch_full": "kandinsky5",
        "required_variant_args": {},
        "train_script": "kandinsky5_train_network.py",
        "cache_latents_script": "kandinsky5_cache_latents.py",
        "cache_te_script": "kandinsky5_cache_text_encoder_outputs.py",
        "generate_script": "kandinsky5_generate_video.py",
        "network_module": "networks.lora_kandinsky",
        "model_files": {
            "dit": "${machine.models_dir}/kandinsky5/kandinsky5_bf16.safetensors",
            "text_encoder_qwen": "${machine.models_dir}/kandinsky5/qwen2_5_vl_7b_bf16.safetensors",
            "text_encoder_clip": "${machine.models_dir}/kandinsky5/clip_l_fp16.safetensors",
            "vae": "${machine.models_dir}/kandinsky5/kandinsky5_vae.safetensors",
        },
        "defaults": {
            "timestep_sampling": "sigmoid",
            "sigmoid_scale": 1.0,
        },
        "dataset_defaults": {
            "default_resolutions": [[512, 512]],
            "video_target_frames": [1, 17, 33, 49, 81],
            "frame_extraction": "head",
        },
        "supports": {
            "mask_loss": True,
            "prior_preservation": True,
            "latent_preview": True,
            "cfg_schedule": True,
            "cfgzerostar": True,
            "nag": False,
            "riflex": False,
            "v2v": False,
            "i2v": True,
            "cute_attention": False,
        },
        "warnings": {},
        "constraints": {},
        "cache_suffix": "kandinsky5",
    },
}

# Build alias lookup at import time
_ALIAS_MAP: dict[str, str] = {}
for _key, _arch in ARCH_REGISTRY.items():
    _ALIAS_MAP[_key] = _key
    for _alias in _arch.get("aliases", []):
        _ALIAS_MAP[_alias] = _key


def resolve_arch(name: str) -> dict[str, Any]:
    """Resolve an architecture name or alias to its registry entry."""
    canonical = _ALIAS_MAP.get(name)
    if canonical is None:
        raise KeyError(f"Unknown architecture: '{name}'. Available: {sorted(ARCH_REGISTRY.keys())}")
    return ARCH_REGISTRY[canonical]


def resolve_arch_key(name: str) -> str:
    """Resolve an architecture name or alias to its canonical key."""
    canonical = _ALIAS_MAP.get(name)
    if canonical is None:
        raise KeyError(f"Unknown architecture: '{name}'. Available: {sorted(ARCH_REGISTRY.keys())}")
    return canonical
